import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import "./globals.css";
import { roboto } from './fonts';
import 'leaflet/dist/leaflet.css'
import { ReduxProvider } from './redux/ReduxProvider';
import TopMenu from '@/Components/Navigation/TopMenu';
import { Providers } from './provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.className} `}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <div className="">
            <TopMenu/>
          </div>
          {children}
        </ReduxProvider>
      </body>
    {/* <html lang="en" className={`${roboto.className}`}>
      <body className="antialiased">
        <Providers>{children}</Providers>
      </body> */}
    </html>
  );
}
